<a href="https://colab.research.google.com/github/MihaiCiorascu/AI-Self-Study/blob/main/Python_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Python

In [ ]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  right = [x for x in arr if x > pivot]
  mid = [x for x in arr if x == pivot]

  return quicksort(left) + mid + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [ ]:
x = 3
print(type(x)) # Prints <class 'int'>
print(x) # Prints 3
print(x + 1) # Prints 4
print(x - 1) # Prints 2
print(x * 2) # Prints 6
print(x ** 2) # Prints 9
print(x // 2) # Prints 1

x += 1
print(x) # Prints 4
x *= 2
print(x) # Prints 8
y = 2.5
print(type(y)) # Prints <class 'float'>
print(y, y + 1, y * 2, y ** 2) # Prints 2.5 3.5 5.0 6.25

<class 'int'>
3
4
2
6
9
1
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [ ]:
t = True
f = False

print(type(t)) # Prints <class 'bool'>
print(t and f) # Prints False
print(t or f) # Prints True
print(not t) # Prints False
print(t != f) # Prints True

<class 'bool'>
False
True
False
True


In [ ]:
hello = 'hello' # String literals can use single quotes
world = "world" # or double quotes; it does not matter
print(hello) # Prints hello
print(len(hello)) # Prints 5
hw = hello + ' ' + world # String concatenation
print(hw) # Prints hello word
hw12 = '%s %s %d' % (hello, world, 12) # sprintf style string formatting
print(hw12) # Prints hello

hello
5
hello world
hello world 12


In [ ]:
s = "hello"
print(s.capitalize()) # Prints Hello
print(s.upper()) # Prints HELLO
print(s.replace('l', '(ell)')) # Prints he(ell)(ell)o
print('  world'.strip()) # Strips the whitespace. Prints world

Hello
HELLO
he(ell)(ell)o
world


### Lists

In [ ]:
# A list in Python is the equivalent of an aray, but resizeable and can contain
# elements of diff types

xs = [3, 1, 2]
print(xs, xs[2])
print(xs[-1]) # Print the last elem
xs[2] = 'foo' # List can contain elems of diff types
print(xs) # Prints 3, 1, foo
xs.append('bar') # Add a new elem at the end
print(xs) # Prints 3, 1, foo, bar
x = xs.pop() # Removes the last elem
print(x, xs)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


### Slicing

In [ ]:
nums = list(range(5)) # range is a built-in fct that creates a list of integers
print(nums) # Prints [0, 1, 2, 3, 4]
print(nums[2:4]) # Prints [2, 3]
print(nums[2:]) # Prints [2, 3, 4]
print(nums[:2]) # Prints [0, 1]
print(nums[:]) # Get a slice of the whole list. Prints [0, 1, 2, 3, 4]
print(nums[:-1]) # Prints [0, 1, 2, 3]
nums[2:4] = [8, 9]
print(nums) # Prints [0, 1, 8, 9, 4]

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


### Loops

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
  print(animal)

cat
dog
monkey


In [ ]:
# If you want access to the index of each element within the body of a loop,
# use the built-in "enumerate" fct

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
  print('%d: %s' % (idx + 1, animal))

1: cat
2: dog
3: monkey


### List comprehensions

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
  squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
# You can make this code simpler using a list comprehension:

nums = [0, 1, 2, 3, 4]
squares = [x**2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
# List comprehensions can also contain conditions:

nums = [0, 1, 2, 3, 4]
squares = [x**2 for x in nums if x%2 == 0]
print(squares)

[0, 4, 16]


### Dictionaries

In [ ]:
# Like a Map in Java

d = {'cat': 'cute', 'dog': 'furry'}
print(d['cat']) # Prints: cute
print('cat' in d) # Prints: True

d['fish'] = 'wet' # Set an entry in dictionary
print(d['fish'])
# print(d['monkey']) # ERROR: monkey is not a key
print(d.get('monkey', 'N/A')) # Get an elem with a default. Prints: N/A
print(d.get('fish', 'N/A')) # Get an elem with a default. Prints: wet

del d['fish'] # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # fish no longer a key => N/A

cute
True
wet
N/A
wet
N/A


### Loops

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for animal in d:
  legs = d[animal]
  print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [ ]:
# If you want access to keys and their corresponding values,
# use "items" method

d = {'person': 2, 'cat': 4, 'spider': 8}

for animal, legs in d.items():
  print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


### Dictionary comprehensions

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x**2 for x in nums if x%2==0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


### Sets

In [ ]:
# An unordered collection of distinct elems.

animals = {'cat', 'dog'}
print('cat' in animals) # Prints: True
print('fish' in animals) # Prints: False

animals.add('fish')
print('fish' in animals) # Prints: True
print(len(animals)) # Prints: 3
animals.add('cat') # Already exists => does nothing
print(len(animals)) # Prints: 3

animals.remove('cat')
print(len(animals)) # Prints: 2

True
False
True
3
3
2


Loops

In [ ]:
# Iterating over a set has the same syntax as iterating over a list;
# however since sets are unordered, you cannot make assumptions about the order
# in which you visit the elements of the set

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
  print("%d: %s" % (idx+1, animal))

1: dog
2: fish
3: cat


Set comprehensions

In [ ]:
from math import sqrt

nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


Tuples

In [ ]:
# A tuple is an immutable ordered list of values. A tuple is in many ways
# similar to a list; one of the most important differences is that tuples can
# be used as keys in dictionaries and as elements of sets, while lists cannot.
# Here is a trivial example:

d = {(x, x + 1): x for x in range(10)} # Create a dictionary with tuple keys
t = (5, 6)
print(type(t)) # Prints: <class 'tuple'>
print(d[t]) # Prints: 5
print(d[1, 2]) # Prints: 1

<class 'tuple'>
5
1


### Classes

In [ ]:
class Greeter(object):

  # Constructor
  def __init__(self, name):
    self.name = name # Create an instance variable

  # Instance method
  def greet(self, loud = False):
    if loud:
      print('HELLO %s' % self.name.upper())
    else:
      print('Hello %s' % self.name)

g = Greeter('Bob')
g.greet()
g.greet(loud=True)

Hello Bob
HELLO BOB


# 2. Numpy

In [ ]:
# Numpy is the core library for scientific computing in Python. It provides a
# high-performance multidimensional array object, and tools for working with
# these arrays.

### Arrays

In [ ]:
# A numpy array is a grid of values, all of the same type, and is indexed by a
# tuple of nonnegative integers. The number of dimensions is in the rank of the
# array; the shape of an array is a tuple of integers giving the size of the
# array along each dimension.

import numpy as np

a = np.array([1, 2, 3]) # Create a rank 1 array
print(type(a)) # Prints: <class 'numpy.array'>

print(a.shape) # Prints: (3, )

print(a[0], a[1], a[2]) # Prints: 1 2 3

a[0] = 5
print(a) # Prints: [5, 2, 3]

b = np.array([[1, 2, 3], [4, 5, 6]]) # Create a rank 2 array
print(b.shape) # Prints: (2, 3)
print(b[0, 0], b[0, 1], b[1, 0]) # Prints: 1, 2, 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
import numpy as np

a = np.zeros((2, 2)) # Create an array of all zeros
print(a)             # Prints: [[0. 0.]]
                     #          [0. 0.]]

b = np.ones((1, 2)) # Create an array of all ones
print(b)            # Prints: [[1. 1.]]

c = np.full((2, 2), 7) # Create a constant array
print(c)               # Prints: [[7. 7.]
                       #          [7. 7.]]

d = np.eye(2) # Create a 2x2 identity matrix
print(d)      # Prints: [[1. 0.]
              #          [0. 1.]]

e = np.random.random((2, 2)) # Create an array filled with random values
print(e)                     # Might print [[ 0.91940167  0.08143941]
                             #              [ 0.68744134  0.87236687]]

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.8684287  0.09784516]
 [0.97964547 0.99091595]]


### Array indexing

Slicing

In [ ]:
# Similar to Python lists, numpy arrays can be sliced. Since arrays may be
# multidimensional, you must specify a slice for each dimension of the array:

import numpy as np

# Create the following rank 2 array with shape(3, 4)
# [[1  2  3  4]
#  [5  6  7  8]
#  [9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it will modify
# the original array.
print(a[0, 1]) # Prints: 2
b[0, 0] = 77 # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) # Prints: 77

2
77


In [ ]:
# Mix integer indexing with slice indexing
# However, doing so will yield an array of lower rank than the original array.

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:
row_r1 = a[1, :] # Rank 1 view of the 2nd row of a
row_r2 = a[1:2, :] # Rank 2 view of the 2nd row of a
print(row_r1, row_r1.shape) # Prints: [5 6 7 8] (4,)
print(row_r2, row_r2.shape) # Prints: [[5 6 7 8]] (1, 4)

# We can make the same distribution when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) # Prints: [2 6 10] (3,)
print(col_r2, col_r2.shape) # Prints: [[2 ]
                            #          [6 ]
                            #          [10]] (3, 1)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing

In [ ]:
# When you index into numpy arrays using slicing, the resulting array view will
# always be a subarray of the original array. In contrast, integer array indexing
# allows you to construct arbitrary arrays using the data from another array

import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,)
# first [] is for row index and 2nd [] is or column index of the aimed integers
print(a[[0, 1, 2], [0, 1, 0]]) # Prints: [1 4 5]

# The above example of integer array indexing is equivalent to:
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # Prints: [1 4 5]

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]]) # Prints: [2 2]

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]])) # Prints: [2 2]

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
# One useful trick with integer array indexing is selecting or mutating one
# element from each row of a matrix:

import numpy as np

# Create a new array from which we will select elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(a) # Prints: array([[1, 2, 3],
         #                [4, 5, 6],
         #                [7, 8, 9],
         #                [10, 11, 12]])

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using indices in b

# np.arange = similar to Python's built-in range() function,
# but returning a NumPy ndarray
print(a[np.arange(4), b]) # Prints: [ 1 6 7 11]

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a) # Prints: array([[11  2  3]
         #                [ 4  5 16]
         #                [17  8  9]
         #                [10 21 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing:

In [1]:
# Boolean array indexing lets you pick out arbitrary elements of an array.
# Frequently this type of indexing is used to select the elements of an array
# that satisfy some condition.

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Datatypes

In [2]:
# Every numpy array is a grid of elements of the same type.
# Numpy provides a large set of numeric datatypes that you can use to construct
# arrays. Numpy tries to guess a datatype when you create an array,
# but functions that construct arrays usually also include an optional argument
# to explicitly specify the datatype.

import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


### Array math

In [5]:
# Basic mathematical functions operate elementwise on arrays, and are available
# both as operator overloads and as functions in the numpy module:

import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [6]:
# Note that unlike MATLAB, * is elementwise multiplication, not matrix
# multiplication. We instead use the dot function to compute inner products of
# vectors, to multiply a vector by a matrix, and to multiply matrices.
# dot is available both as a function in the numpy module and as an
# instance method of array objects:

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [7]:
# Numpy provides many useful functions for performing computations on arrays;
# one of the most useful is sum:

import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x)) # Compute sum of all elems; Prints: 10
print(np.sum(x, axis=0)) # Compute sum of each column; Prints: [4 6]
print(np.sum(x, axis=1)) # Compute sum of each row; Prints: [3 7]

10
[4 6]
[3 7]


In [8]:
# Apart from computing mathematical functions using arrays, we frequently need
# to reshape or otherwise manipulate data in arrays. The simplest example of
# this type of operation is transposing a matrix; to transpose a matrix,
# simply use the T attribute of an array object:

import numpy as np

x = np.array([[1, 2], [3, 4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### Broadcasting

In [9]:
# is a powerful mechanism that allows numpy to work with arrays of different
# shapes when performing arithmetic operations. Frequently we have a smaller
# array and a larger array, and we want to use the smaller array multiple times
# to perform some operation on the larger array.

# For example, suppose that we want to add a constant vector to each row of
# a matrix. We could do it like this:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)    # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
  y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [10]:
# This works; however when the matrix x is very large, computing an explicit
# loop in Python could be slow. Note that adding the vector v to each row of
# the matrix x is equivalent to forming a matrix vv by stacking multiple copies
# of v vertically, then performing elementwise summation of x and vv.

# We could implement this approach like this:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)         # Prints "[[1 0 1]
                  #          [1 0 1]
                  #          [1 0 1]
                  #          [1 0 1]]"

y = x + vv    # Add x and vv elementwise
print(y)     # Prints "[[ 2  2  4
             #          [ 5  5  7]
             #          [ 8  8 10]
             #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# Numpy broadcasting allows us to perform this computation without actually
# creating multiple copies of v. Consider this version, using broadcasting:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v     # Add v to each row of x using broadcasting

print(y)      # Prints [[ 2  2  4]
              #          [ 5  5  7]
              #          [ 8  8 10]
              #          [11 11 13]]

The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [ ]:
# Functions that support broadcasting are known as universal functions.
# Here are some applications of broadcasting:

import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

A more detailed version can be found here:

https://cs231n.github.io/python-numpy-tutorial/